stages:
  - build
  - test


Build Image:
  image: jonoh/docker-buildx-qemu
  stage: build
  services:
    - docker:19.03.0-dind
  before_script:
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || echo 'No previous image to download as a base'
    - docker build -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push "$CI_REGISTRY_IMAGE:latest"
  except:
    - tags

test:
  stage: test
  image: $CI_REGISTRY_IMAGE:latest
  script:
  - cd $CI_PROJECT_DIR
  - pip install -e .
  - python --version
  - pipenv --version
  - ./run_tests.sh

