version: '2.3'
services:
  benchmark-tools:
    image: registry.insight-centre.org/sit/mps/benchmark-tools:latest
    command: python /service/benchmark_tools/controller/controller.py
    build:
      context: '.'
      dockerfile: 'Dockerfile'
      args:
        SIT_PYPI_USER_VAR: ${SIT_PYPI_USER}
        SIT_PYPI_PASS_VAR: ${SIT_PYPI_PASS}
    ports:
      - "8000:8000"
    volumes:
      - ./:/service
    environment:
      - PYTHONUNBUFFERED=0
      - BENCHMARK_JSON_CONFIG_PATH=${BENCHMARK_JSON_CONFIG_PATH}
      - TARGET_SYSTEM_JSON_CONFIG_PATH=${TARGET_SYSTEM_JSON_CONFIG_PATH}
      - RESULT_WEBHOOK_URL=${RESULT_WEBHOOK_URL}
