version: '2.3'
services:
  benchmark-tools:
    image: arruda/benchmark-tools:master
    working_dir: /service
    command: python /service/benchmark_tools/controller/controller.py
    build:
      context: '.'
      dockerfile: 'Dockerfile'
      args:
        SIT_PYPI_USER_VAR: ${SIT_PYPI_USER}
        SIT_PYPI_PASS_VAR: ${SIT_PYPI_PASS}
    # ports:
    #   - "8000:8000"
    volumes:
      - ./outputs:/service/outputs
      - ./benchmark_tools:/service/benchmark_tools
    environment:
      - PYTHONUNBUFFERED=0
