version: '2.3'
services:
  benchmark-tools:
    image: registry.insight-centre.org/sit/mps/benchmark-tools:felipe-phd
    command: python /service/benchmark_tools/controller/controller.py
    build:
      context: '.'
      dockerfile: 'Dockerfile'
      args:
        SIT_PYPI_USER_VAR: ${SIT_PYPI_USER}
        SIT_PYPI_PASS_VAR: ${SIT_PYPI_PASS}
    volumes:
      - ./:/service
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=0
